### PR TITLE
Microverse template 1 project contact section

### PR DESCRIPTION
**Pull request by Rustamxon7**
I have created this branch to check my contact section.
We did pair programming to create the contact section.

### CODE REVIEW

**Comment by mikenath223** [comment]
Hi , 

You made a great effort in this project, but unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that will be invalidated for this reason:
- Please ensure GitHub actions linting checks run and are all green.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Happy coding. Cheers!🚀🚀

If something isn't 100% clear, you can leave comments or questions in this PR thread.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, whether valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **don't count** into the code reviews limit._

**Comment by Rustamxon7** [comment]
> Hi ,
> 
> You made a great effort in this project, but unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request
> You have submitted a project, that will be invalidated for this reason:
> 
> * Please ensure GitHub actions linting checks run and are all green.
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Happy coding. Cheers!🚀🚀
> 
> If something isn't 100% clear, you can leave comments or questions in this PR thread.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, whether valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **don't count** into the code reviews limit._

I did upload it after checking liter errors, please can you check it again?

**Review by vichuge — CHANGES_REQUESTED** [review]
# Required Changes ♻️ ⚠️ 🚦 

Hi dear student, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

mario_ladders

## Good points 👍 
You used proper GitHub Flow ✔️
Your linter checks are all passing ✔️
Your README and PR message are descriptive ✔️

## Aspects to improve ♻️

- [ ] It looks like you have a little bug on the navbar, the options appear where should be the burger icon, these options will be shown in the future with an interactive navbar or on desktop size, but now is not necessary. I kindly invite you to fix it. 🐶 
image


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Rustamxon7** [comment]
> # Required Changes ♻️ ⚠️ 🚦
> Hi dear student,
> 
> Good job so far!
> You still need to work on some issues to go to the next project, but you are almost there!
> 
> mario_ladders
> 
> ## Good points 👍
> You used proper GitHub Flow ✔️
> Your linter checks are all passing ✔️
> Your README and PR message are descriptive ✔️
> 
> ## Aspects to improve ♻️
> * [x]  It looks like you have a little bug on the navbar, the options appear where should be the burger icon, these options will be shown in the future with an interactive navbar or on desktop size, but now is not necessary. I kindly invite you to fix it. 🐶
>   image
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

I have completed it can you check it.

**Review by rloterh — APPROVED** [review]
## Status: Approved :heavy_check_mark:

Hi Rostam and Dannie , 

Your project is complete! Great job for making the necessary changes recommended by the previous reviewer. There is nothing else to say other than... it's time to merge it 🍾  👍.
Congratulations! 🎉🥂


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 1 more limited review per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Rustamxon7** [comment]
> ## Status: Approved ✔️
> Hi Rostam and Dannie ,
> 
> Your project is complete! Great job for making the necessary changes recommended by the previous reviewer. There is nothing else to say other than... it's time to merge it 🍾 👍.
> Congratulations! 🎉🥂
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 1 more limited review per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Thank you so much for patiently reviewing my code. I'm happy to see that message _Your project is complete!_ 🥳🎉

**Pull request merged**
